spring:
  alarm:
    initOsfAlarmCenterDb: false # 自动初始化通道，上线后关闭
    ofsOrderRedisKeyExpiredTime: 14400
    ofsShopCenterDb: ofs_shop_center
    ofsPickCenterDb: picklist_db
    ofsDeliveryCenterDb: ofs_delivery_center
    databases:
      # 配置中心表
      - name: ${spring.alarm.ofsShopCenterDb}
        tables:
          - name: shop_config_info
            columns:
              - name: name
                type: varchar
                descr: name=Delivery 配置key的名称
              - name: value
                type: varchar
                descr: name=Delivery&&value=1|3|4为系统派单
      # 仓内作业拣货打包表
      - name: ${spring.alarm.ofsPickCenterDb}
        tables:
          - name: t_trade_picklist_order
            columns:
              - name: start_pick_time
                type: datetime
                descr: 拣货开始时间
              - name: finish_pick_time
                type: datetime
                descr: 拣货结束时间

              - name: order_id
                descr: 订单id
                ignore: true
              - name: shop_id
                ignore: true
                descr: 仓店id
              - name: seller_id
                ignore: true
                descr: 商家id

              - name: picker_id
                ignore: true
                descr: 拣货人id
              - name: picker_name
                ignore: true
                descr: 拣货人姓名

              - name: packer_id
                ignore: true
                descr: 打包人id
              - name: packer_name
                ignore: true
                descr: 打包人姓名
      # 配送单表
      - name: ${spring.alarm.ofsDeliveryCenterDb}
        tables:
          - name: t_delivery_order
            columns:
              - name: id
                descr: 配送单主键id
                type: bigint
              - name: status
                type: int
                descr: 状态(0:待准备,10:待派单,20:待接单,30:待提货,40:待出发,50:待到达,60:待妥投,70:待确认,80:已完成,90:已关闭,100:已取消)
              - name: end_time
                type: datetime
                descr: 结单时间
              - name: dispatch_time
                type: datetime
                descr: 派单时间
              - name: pickup_time
                type: datetime
                descr: 提货时间
              - name: delivery_releasable_time
                type: datetime
                descr: 配送可释放时间
              - name: delivery_deadline_time
                type: datetime
                descr: 配送截止时间


              - name: order_id
                ignore: true
                descr: 订单id
              - name: shop_id
                ignore: true
                descr: 仓店id

              - name: rider_id
                ignore: true
                descr: 骑手id
              - name: rider_name
                descr: 骑手姓名
                ignore: true
              - name: rider_mobile
                descr: 骑手电话
                ignore: true
          # 配送异常单表
          - name: t_delivery_exception_order
            columns:
              - name: delivery_order_id
                type: bigint
                descr: 配送单号
              - name: delivery
                type: int
                descr: 配送状态(0:未配送,1:已配送)

              - name: order_id
                ignore: true
                descr: 订单id
              - name: shop_id
                ignore: true
                descr: 仓店id
              - name: rider_id
                ignore: true
                descr: 骑手id
              - name: rider_remark
                ignore: true
                descr: 骑手备注
