server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #配置路由路径
        - id: auth-api-route
          uri: lb://arch-demo-auth-crud
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: auth-oauth2-route
          uri: lb://auth-oauth2
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ea98d9632e9af11db7ce
            client-secret: 4a7a7cc6fe988537f23a9dbabebc0ff24b46a7b3
#          gitee:
#            client-id: e4d328c8f5b322d87ddfbfd335cc104fc26d0a6327c231ac6735b36f0428d5ef
#            client-secret: 021d70e32c539776b63f3b11cb9b288aef37010dc8d33f0c34a15f95decb6443
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
#    password: 123456
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"