---
#生产环境
spring:
  config:
    activate:
      on-profile: pro


---
#开发环境
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  redis:
    #数据库索引
    database: 0
    host: 192.168.71.15
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
