package ${package!""};

import org.arch.framework.api.crud.BaseRequestDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 *  ${(name?cap_first)!""} Dto generated by auto
 * ${comment!""}
 *
 * @author ${author!""}
 * @date ${.now}
 * @since  1.0.0
 */
@Data
@NoArgsConstructor
@Accessors(chain = true)
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class ${(name?cap_first)!""}${suffix!""} extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    <#if columns?? && (columns?size > 0)>
    <#list columns as column>
    /**
     * ${column.comment!""}
     */
    // TODO 增加对列(xx_xx)转换为驼峰类型字段, 不能获取数据库类型对应的 JavaType
    private ${(column.name?cap_first)!""} ${(column.name?uncap_first)!""};

    </#list>
    </#if>
}

