package ${packageName};

import java.util.Map;

import org.arch.framework.api.crud.BaseSearchDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
<#list imports as import>
import ${import};
</#list>

/**
 * ${entity.className} Dto generated by auto
 * ${comments}
 *
 * @author ${author}
 * @since ${date}.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ${className} extends BaseSearchDto{


    <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    /**
     * TODO 字段信息描述
     */
    private ${f.className} ${f.name};

    </#list>
    </#if>
    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
        super.putNoNull("EQ_${f.name}", this.${f.name}, map);
    </#list>
    </#if>
    }

}
