server:
  port: 9402
spring:
  application:
    name: auth-oauth2
  resources:
    static-locations: classpath:/public
  thymeleaf:
    enabled: true
    cache: false
    mode: html
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
#    password: 123456

  profiles:
    active: dev,db
management:
  endpoints:
    web:
      exposure:
        include: "*"
