spring:
#  datasource:
#    dynamic:
#      hikari:
#        connection-test-query: SELECT 1
#        connection-timeout: 30000
#        max-lifetime: 1800000
#        max-pool-size: 15
#        min-idle: 5
#      primary: master

  datasource:
    dynamic:
      hikari:
        connection-test-query: SELECT 1
      primary: master
      datasource:
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
          username: "root"
          password: "123456"
          hikari:
            max-pool-size: 10
            min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: org.arch.auth.rbac.entity
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    #    datacenter-id: ${nodeId:${spring.nodeId:1}}
    #    worker-id: ${nodeId:${spring.nodeId:1}}
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null