server:
  port: 9401
  servlet:
    context-path: /sso
spring:
  application:
    name: auth-sso
  web:
    resources:
      static-locations: classpath:/public
  thymeleaf:
    enabled: true
    cache: true
    mode: html
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .htm

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    loadbalancer:
      ribbon:
        enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  profiles:
    include: auth,arch,db,mdc,oauth2,feign,redis,vc,jwt,rbac
    active: ${profile:dev}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


logging:
  config: classpath:logback-spring.xml



---
server:
  port: 9401

spring:
  config:
    activate:
      on-profile: dev

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.2:8848

  thymeleaf:
    cache: false


  mvc:
    throw-exception-if-no-handler-found: true


logging:
  config: classpath:logback-spring-dev.xml
  level:
    # feign 日志配置
    org.arch.auth.ums.feign.client.ArchUmsAccountClient: debug

debug: true