arch:
  sso:
    # 手机用户默认密码
    default-password: "VR&vU'a#.mt^&%'"
    # 默认用户头像
    default-avatar: "http://static.dcenter.top/static/img/random/user/14.jpg"
    # 用户注册成功后的默认权限, 多个权限用逗号分开, 默认为: "ROLE_USER"
    default-authorities: ROLE_USER
    # 第三方登录成功后, 返回获取 token 自动脚本页面. 默认: /oauth2Token
    auto-get-token-uri: /oauth2Token
    # 第三方登录成功后, autoGetTokenUrl 获取 token 处理接口 url, 默认: /oauth2Callback
    oauth-2-callback-uri: /oauth2Callback
    # 第三方登录成功后, oauth2CallbackUri 接收的参数名称, 默认: tk
    oauth-2-token-param-name: tk
    # 存储 OAuth2Token 的临时缓存前缀: 默认: TEMP:OAuth2Token:
    temp-oauth-2-token-prefix: 'TEMP:OAuth2Token:'
    # token 与 refreshToken 的分隔符: 默认: #@#
    delimiter-of-token-and-refresh-token: '#@#'
    # 第三方登录成功后, 临时存储在 redis 的 token 值的 TTL, 默认: 30 秒
    temp-oauth-2-token-timeout: PT30S
  app:
    client-id: "001"
    client-secret: "001"
    systemTenantId: "0"
  encrypt:
    fpe:
      password: 8CE4A06235DACD71AD9CA11C5AF21B8C
      tweak: D9C4BC2E11C8FBAA  # tweak, used in each round and split into right and left sides; fixed length: 16.
      radix: 10       # radix: 10(数字), 26(数字加前16个小写字母), 36(数字加26个小写字母)
    text-encryptor:
      password: AA2DB91EED5CA9F4C1D2DFBFA592666C
      salt: 6B2EDFD8C0BB6C03
    totp:
      key: CWYMX4TZK4O2MMBHMTBKT45A2OTL6NTZMSBYH3VLZTTDTQHRH6ZSHG8G2ZDFH21LZ1XCXB0ZEHTKHNLDNBKXJT8LKO1GLLXY8WV5FO2XSYMAIMONU6QHS1ZSDSVLKMBXZBOV9D5TYMLMVGZ1KFYRH9UOZ2VN0ZXO
      crypto: HmacSHA1
      returnDigits: 8
      slidingWindow: 30S
  file:
    # 图片文件存放的 url. 默认: ""
    url: "http://localhost:9090/sso"
    # 图片文件存放的根目录. 默认: /image/account/
    root-path: "/image/account/"
    # 上传的类型, 即目录名称. 默认: avatar
    upload-type: "avatar"
    # 允许最大的上传图片大小, 默认: 2 * 1024 * 1024
    image-max-size: 2097152

  retry:
    delay: 1500
    max-attempts: 2
    time-unit: milliseconds


---
spring:
  config:
    activate:
      on-profile: dev

arch:
  sso:
    default-avatar: http://static.dcenter.top/static/img/random/user/14.jpg
    temp-oauth-2-token-timeout: PT300S
  file:
    # 图片文件存放的 url. 默认: ""
    url: "D:/Workspaces-Idea/proc/arch-module/arch-auth/auth-sso/target"
    # 图片文件存放的根目录. 默认: /image/account/
    root-path: "/image/account/"
    # 上传文件的分类, 即目录名称. 默认: avatar
    upload-type: "avatar"
    # 允许最大的上传图片大小, 默认: 2 * 1024 * 1024
    image-max-size: 2097152