server:
  port: 9401
  servlet:
    context-path: /sso
spring:
  application:
    name: auth-sso
  resources:
    static-locations: classpath:/public
  thymeleaf:
    enabled: true
    cache: false
    mode: html
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .htm

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.2:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
#    password: 123456

  profiles:
    include: auth,arch,db,mdc,oauth2,redis,vc,jwt



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


logging:
  config: classpath:logback-spring.xml
