server:
  port: 9401

spring:
  #  datasource:
  #    dynamic:
  #      hikari:
  #        connection-test-query: SELECT 1
  #        connection-timeout: 30000
  #        max-lifetime: 1800000
  #        max-pool-size: 15
  #        min-idle: 5
  #      primary: master

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  redis:
    host: 192.168.50.2
    port: 6379
    password:
    database: 0
    # 连接超时的时间
    timeout: 10000
    # redis-lettuce-pool
    lettuce:
      # 会影响应用关闭是时间, dev 模式设置为 0
      shutdown-timeout: PT000S
      pool:
        max-active: 8
        max-wait: PT10S
        max-idle: 8
        min-idle: 1


  thymeleaf:
    cache: false

  mvc:
    throw-exception-if-no-handler-found: true


#  profiles:
#    active: dev,db,auth,oauth2,vc,jwt
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring-dev.xml
