ums:
  # 验证码配置
  codes:
    # 验证码缓存类型, 默认: SESSION, 可选: REDIS/SESSION
    validate-code-cache-type: session
    # 获取验证码的 url 的前缀, 默认: /code
    validate-code-url-prefix: /code
    # ===== 刷新图片验证码与滑块验证码缓存 定时任务 属性 =====
    # A cron-like expression.
    # 0 * 4 * * ? 分别对应: second/minute/hour/day of month/month/day of week
    # 默认为: "0 * 4 * * ?", 凌晨四点
    refresh-validate-code-job-cron: 0 * 4 * * ?
    # 是否支持定时刷新 validateCodeJob 定时任务, 考虑到很多应用都有自己的定时任务应用, 默认: false. RefreshValidateCodeCacheJob 接口的实现已注入 IOC 容器, 方便自定义定时任务接口时调用.
    enable-refresh-validate-code-job: true
    # 定时刷新 validateCodeJob 任务时, 需要缓存的验证码图片数. 默认: 100;
    # 注意: 这里为了方便开发而设置的值, 生产环境根据情况直接设置
    total-images: 100
    # 图片验证码
    image:
      # 设置需要图片验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “-” 或 ","号分开支持通配符，如：/hello,/user/*；默认为 /authentication/form
      auth-urls:
        - /authentication/form
        - /authentication/social
      # 验证码长度
      length: 4
      # 图片验证码高
      height: 60
      # 图片验证码宽
      width: 270
      # 验证码过期时间
      expire: 180
      # 验证码 request 参数名称
      request-param-image-code-name: imageCode
      # 缓存图片验证码目录，默认 classpath:static/image/code,
      # 不以 "classpath:" 开头时即认为是绝对路径, 以 "classpath:" 开头时即认为是基于 classpath 的相对路径.
      image-cache-directory: classpath:static/image/code

    # 滑块验证码
    slider:
      # 设置需要验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “-” 或 ","号分开支持通配符，如：/hello,/user/*；默认为 空
      auth-urls:
        - /authentication/form
        - /slider/check
      # 设置滑块验证码校验证的 uri, 默认: /slider/check, 默认: /slider/check
      slider-check-url: /slider/check
      # 提交验证码请求时，请求中带的验证码变量名，默认 sliderCode.
      # 与 tokenRequestParamName, xRequestParamName, yRequestParamName 互斥关系;
      # 当使用此参数时, 把另外三个参数(kv键值对形式, 键值对之间用逗号风隔) 组装到此参数.
      # 注意: 默认传递参数是用另外的三个参数实现验证码校验, 如要使用此参数, 请重新实现 ValidateCodeProcessor#validate(ServletWebRequest)
      request-param-name: sliderCode
      # request token param name, 默认: sliderToken. 与 requestParamName 互斥关系.
      token-request-param-name: sliderToken
      # request X param name, 默认: x. 与 requestParamName 互斥关系.
      x-request-param-name: x
      # request Y param name, 默认: y. 与 requestParamName 互斥关系.
      y-request-param-name: y
      # 在模板上抠图区灰阶等级: 4-10, 数值越高, 灰色越深, 默认: 5
      grayscale: 5
      # 模板图片与原始图片的图片后缀, 默认: png
      imageSuffix: png
      # 滑块验证码默认过期时间, 180 秒
      expire: 180
      # 原始图片目录，默认 classpath:static/image/slider/original
      # 不以 "classpath:" 开头时即认为是绝对路径, 以 "classpath:" 开头时即认为是基于 classpath 的相对路径.
      original-image-directory: classpath:static/image/slider/original
      # 模板图片目录, 模板图片必须符合: 模板图片的宽 * 3 < 原始图片的宽, 且 模板图片的高 *2 < 原始图片的高; 背景必须是白色, 默认 classpath:static/image/slider/template,
      # 不以 "classpath:" 开头时即认为是绝对路径, 以 "classpath:" 开头时即认为是基于 classpath 的相对路径.
      template-image-directory: classpath:static/image/slider/template
      # 根据原始图片生成的滑块图片目录，用于自定义缓存滑块图片的存储目录, 默认 classpath:static/image/slider/code,
      # 不以 "classpath:" 开头时即认为是绝对路径, 以 "classpath:" 开头时即认为是基于 classpath 的相对路径.
      code-image-directory: classpath:static/image/slider/code


    # 短信验证码
    sms:
      # 设置需要短信验证码认证的 uri(必须是非 GET 请求)，多个 uri 用 “，”号分开支持通配符，如：/hello,/user/*；默认为 /authentication/form
      auth-urls:
        - /authentication/mobile
      length: 6
      expire: 120
      request-param-mobile-name: mobile
      request-param-sms-code-name: smsCode
