server:
  port: 9401
  servlet:
    context-path: /sso

spring:
  application:
    name: auth-sso
  resources:
    static-locations: classpath:/public
  thymeleaf:
    enabled: true
    cache: false
    mode: html
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .htm

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.2:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.50.2
    port: 6379
    password:
    database: 0
    # 连接超时的时间
    timeout: 10000
    # redis-lettuce-pool
    lettuce:
      # 会影响应用关闭是时间, dev 模式设置为 0
      shutdown-timeout: PT000S
      pool:
        max-active: 8
        max-wait: PT10S
        max-idle: 8
        min-idle: 1

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  mvc:
    throw-exception-if-no-handler-found: true

  profiles:
    include: auth,arch,db,mdc,oauth2,redis,vc,jwt

arch:
  sso:
    default-avatar: http://static.dcenter.top/static/img/random/user/14.jpg


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-spring-dev.xml
  level:
    # feign 日志配置
    org.arch.auth.ums.feign.client.ArchUmsAccountClient: debug

debug: true
