arch:
  # 默认用户头像
  default-avatar: http://static.dcenter.top/static/img/random/user/14.jpg
  # 第三方登录成功后, 返回获取 token 自动脚本页面. 默认: /oauth2Token
  auto-get-token-uri: /oauth2Token
  # 第三方登录成功后, autoGetTokenUrl 获取 token 处理接口 url, 默认: /oauth2Callback
  oauth-2-callback-uri: /oauth2Callback
  # 第三方登录成功后, oauth2CallbackUri 接收的参数名称, 默认: tk
  oauth-2-token-param-name: tk
  # 存储 OAuth2Token 的临时缓存前缀: 默认: TEMP:OAuth2Token:
  temp-oauth-2-token-prefix: 'TEMP:OAuth2Token:'
  # token 与 refreshToken 的分隔符: 默认: #@#
  delimiter-of-token-and-refresh-token: '#@#'
  # 第三方登录成功后, 临时存储在 redis 的 token 值的 TTL, 默认: 30 秒
  temp-oauth-2-token-timeout: PT30S