#server:
#  port: 8088

spring:
  application:
    name: application
  profiles:
    active: dev,db
  redis:
    host: redis.kancy.top
    port: 6379
    password: root123
    database: 10

mica:
  lock:
    address: redis://47.100.244.76:6379
    password: root123

