package ${package!""};

import org.arch.framework.api.crud.BaseRequestDto;

import lombok.Data;
import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *  ${(name?cap_first)!""} Dto generated by auto
 * ${comment!""}
 *
 * @author ${author!""}
 * @date ${.now}
 * @since  1.0.0
 */
@Data
@NoArgsConstructor
@Accessors(chain = true)
@ToString(callSuper = true)
public class ${(name?cap_first)!""}${suffix!""} implements Serializable  {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    <#if columns?? && (columns?size > 0)>
    <#list columns as column>
    /**
     * ${column.comment!""}
     */
    <#if column?? && ((column == "appId") || (column == "storeId") || (column == "rev"))>
    @JsonIgnore
    </#if>
    // TODO 增加对列(xx_xx)转换为驼峰类型字段, 不能获取数据库类型对应的 JavaType
    private ${(column.name?cap_first)!""} ${(column.name?uncap_first)!""};

    </#list>
    </#if>
}

