server:
  port: 8081
  servlet:
    context-path: /pay

spring:
  profiles:
    include: db,redis
    active: ${profile:dev}
  jackson:
    time-zone: GMT+8

logging:
  name: application-payment
  config: classpath:logback-spring.xml
