spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: org.arch.application.form.domain
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    datacenter-id: ${nodeId:${spring.nodeId:1}}
    worker-id: ${nodeId:${spring.nodeId:1}}
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null


---
#生产环境
spring.profiles: db-pro


---
#开发环境
spring.profiles: db-dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arch?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: root
    password: root



