spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:form-schema.sql
    data: classpath:form-data.sql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: org.arch.automate.form.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
      # db前缀 如：arch.upload_form
#      table-prefix: arch
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null


#虽然两种都可以运行成功，但下面这种写法才是2.4版本的最好的写法，原因是2.4版本中官方将配置文件的加载进行了更新，
#所以如果使用的是2.4版本推荐用下面的这种写法，至于原因就是为了提升对 Kubernetes 的原生支持而作的修改
#spring:
#  profiles: pro
---
#生产环境
spring:
  config:
    activate:
      on-profile: pro


---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    dynamic:
      strict: false
      datasource:
        master_form:
          username: root
          password: late856147
          url: jdbc:mysql://139.224.225.88:3306/arch_module?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
        master_ddl:
          username: root
          password: late856147
          url: jdbc:mysql://139.224.225.88:3306?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000



