builder:
  author: lait
  comments: 这是类的注释
  cover: true
  template:
    dir: src/main/resources/templates
  base:
    project:
      #path:
  entity:
    package: org.arch.demo.test.entity
    template: entity.ftl
    suffix:
    id:
      class: Integer
      package:
  dto:
    package: org.arch.demo.test.dto.request
    template: dto.ftl
    suffix: RequestDto
  response:
    package: org.arch.demo.test.dto.response
    template: response.ftl
    suffix: Response
  search:
    package: org.arch.demo.test.dto.search
    template: search.ftl
    suffix: SearchDto
  controller:
    package: org.arch.demo.test.endpoint
    template: endpoint.ftl
    suffix: Endpoint
  service:
    package: org.arch.demo.test.service
    template: service.ftl
    suffix: Service
  repository:
    package: org.arch.demo.test.repository
    template: repository.ftl
    suffix: Repository
  db:
    driver: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/uni?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: root
