server:
  port: 8082
  servlet:
    context-path: /portal
  #netty 实现
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
      io: 4
      # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
      # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
      worker: 32

spring:
  freemarker:
    check-template-location: false
    settings:
      classic_compatible: true

  profiles:
    include: db,redis
    active: ${profile:dev}



#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJDE8njvcSdtnRL0wqRWwLvrdCoLmXz6hSWLkcGrFDtN5tkbg13I54V34pB2WbIl0cs2iPvkyf/lHrA1wociJFX9oxgzRBz57rS9/SxaafFxZz76nDFcTu/rHLHv8s3So0kLpH/h9suYysRPFZVKl+Tmc+fILgnQ6tPf2k9Y/NaxAgMBAAECgYAEFrvudHzSq0LjdSxGLfkVlanbQiacpAq8q7t7J9TTc/jQKvnD3VfEqkUo5V7VLEJHpguqaaTW6Ga8fVg4Ltut0vFNm3UneTtVMQGM8kcyaHSmdhMOIJYLh5qFJU7oPIDhy6b3GS8GzK7kQ762HuQznIdFU8jtOeavi7Jc65ugUQJBAO8yaILrvRo8LWG6meq2TVg6QrKmF7EZO73m93aGHW0JRO1zOYdMYCThgk324Hy5cf7gR+yjKoGTfliTRuZQ8F0CQQCa8GcczukEg08GIfBeQXIUmoiPHcP4W/92XZgy4eUsDQsY+FQGj1CGEldad6dxk2syakqnpLvKKr0QoCdLLeplAkEAhgzB9V0XxTQkWriwuZEhF2jPKD9c16tEh9CArrPKmeiv8EK64tAysXiQBhFtDXkAIc6fgEaQ870s+YbQHRMPIQJBAIm9ao2LzE+8xEX5ag0BNX/nmbtRhOSINOVvc1zYwbmVpuX97gUe50EpkQrWEL/BhKz/HXtH0cJ6mDXtisElApkCQQCHUj07ve+Vu4CjBRwoehZ818IKOSfedKdGPez6AeAslb7oP+NeI68ycH5UXY6d8L495SLJYXtzByoWCi7PWcHn

smsCode:
  expiration: 5
  maxCount: 10


serviceUrl:
  clients:
    -
      service-a: http://
    -
      service-b: http://
