spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
      username: "root"
      password: "123456"
      maximum-pool-size: 10
      minimum-idle: 5
    url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: "root"
    password: "123456"
#  datasource:
#    dynamic:
#      hikari:
#        connection-test-query: SELECT 1
#      primary: master
#      datasource:
#        master:
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
#          username: "root"
#          password: "123456"
#          hikari:
#            max-pool-size: 10
#            min-idle: 5





mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: org.arch.ums.account.entity,org.arch.ums.user.entity
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
#    datacenter-id: ${nodeId:${spring.nodeId:1}}
#    worker-id: ${nodeId:${spring.nodeId:1}}
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: org.arch.framework.ums.enums