server:
  port: 8088
  servlet:
    context-path: /ums
spring:
  application:
    name: arch-ums-api
  freemarker:
    check-template-location: false
    settings:
      classic_compatible: true
  profiles:
    active: db,dev
  jackson:
    time-zone: GMT+

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  config: classpath:logback-spring.xml
