server:
  port: 9097
  servlet:
    context-path: /ums
spring:
  application:
    name: arch-ums-api
  freemarker:
    check-template-location: false
    settings:
      classic_compatible: true
  jackson:
    time-zone: GMT+

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  profiles:
    include: db,redis,arch,rocketmq,feign
    active: ${profile:dev}

logging:
  config: classpath:logback-spring.xml
  level:
    org.arch.ums: warn
    org.arch.auth: warn
    top.dcenter: warn
    com.alibaba.cloud.stream.binder.rocketmq: warn
---
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


logging:
  config: classpath:logback-spring-dev.xml
  # feign 日志配置
  level:
    org.arch.ums: info
    org.arch.auth: info
    top.dcenter: info
    com.alibaba.cloud.stream.binder.rocketmq: debug