spring:
  config:
    activate:
      on-profile: prod

arch:
  app:
    client-id: "003"
    client-secret: "003"

  csrf:
    # 是否支持 csrf, 默认: true
    enable: false


---
spring:
  config:
    activate:
      on-profile: dev

arch:
  app:
    client-id: "003"
    client-secret: "003"

  csrf:
    # 是否支持 csrf, 默认: true
    enable: false
    # 需要忽略 csrf 校验的 POST 请求.
    ignoring-ant-matcher-urls:
      - '/account/oauthClient/scopes'