server:
  port: 8088
  servlet:
    context-path: /ums
spring:
  application:
    name: arch-ums-api
  freemarker:
    check-template-location: false
    settings:
      classic_compatible: true
  jackson:
    time-zone: GMT+

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  profiles:
    include: db,redis,arch
    active: ${profile:dev}

logging:
  config: classpath:logback-spring.xml
  # feign 日志配置
  level:
    org.arch.ums.account.client.ArchUmsAccountClient: error

---
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.2:8848


logging:
  config: classpath:logback-spring-dev.xml
  # feign 日志配置
  level:
    org.arch.ums.account.client.ArchUmsAccountClient: info